---
#######################################################################
#
# HBTS SYSTEM COMPOSE FILE
#
# This Docker Compose configuration file sets a Docker network
# resembling the production system environment hosting the
# application.
#
# In addition to the environment variables recognized by the
# application, the following variables configure the behavior of the
# spawned containers:
#
# HBTS_HTTP_PORT:
#   Specifies the port to which the HTTP server binds (default: 8443).
# HBTS_RDBMS_PORT:
#   Specifies the port to which the Relational Database Management
#   System (RDBMS) binds.
# HBTS_AMQP_PORT:
#   Specifies the port to which the Aorta backend binds (default: 5672).
#   Consumers may connect to this port in order to *receive* messages
#   published in the system.
# HBTS_MQADM_PORT:
#   Specifies the port to which the administrative web interface of
#   the message broker backend binds (default: 8161).
#
#######################################################################
version: '3'
services:
  hbts_migrations:
    build: .
    environment:
    - HBTS_RUNTIME=migrations
    - HBTS_SECRET_KEY=197fb52f8305c461a677256c3cb588e64936dc814e8fcda98f5a0148be514da6
    - HBTS_DEBUG=1
    - HBTS_IOC_DEFAULTS=/etc/hbts/ioc.conf
    - HBTS_IOC_DIR=/etc/hbts/ioc.conf.d/
    - HBTS_RDBMS_DSN=postgresql+psycopg2://hbts:hbts@rdbms:5432/hbts
    depends_on:
    - rdbms
  hbts:
    build: .
    environment:
    - HBTS_RUNTIME=${HBTS_RUNTIME-service}
    - HBTS_SECRET_KEY=197fb52f8305c461a677256c3cb588e64936dc814e8fcda98f5a0148be514da6
    - HBTS_DEBUG=1
    - HBTS_IOC_DEFAULTS=/etc/hbts/ioc.conf
    - HBTS_IOC_DIR=/etc/hbts/ioc.conf.d/
    - HBTS_RDBMS_DSN=postgresql+psycopg2://hbts:hbts@rdbms:5432/hbts
    depends_on:
    - rdbms
    volumes:
    - "./etc:/etc/hbts:ro"
    expose:
    - "8443"
  http:
    image: nginx:1.15.0-alpine
    volumes:
    - "./etc/certs/snakeoil.crt:/etc/ssl/certs/snakeoil.crt:ro"
    - "./etc/private/snakeoil.pem:/etc/ssl/private/snakeoil.pem:ro"
    - "./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
    - "127.0.0.1:${HBTS_HTTP_PORT-8443}:443"
  rdbms:
    image: postgres:10.3-alpine
    restart: always
    environment:
    - POSTGRES_DB=hbts
    - POSTGRES_USER=hbts
    - POSTGRES_PASSWORD=hbts
    expose:
    - 5432
    ports:
    - "127.0.0.1:${HBTS_RDBMS_PORT-5432}:5432"
