---
#######################################################################
# OpenAPI definition for the  application.
#
# NOTES:
#
# - Endpoints are configured with the `x-endpoint` attribute.
# - Schema definitions of `requestBody`, for any content type,
#   is assumed to be defined in `components` and referenced.
#
#######################################################################
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Hash-based Time Stamping (HBTS) Service
  description: >
    Provides an API to create secure time stamps of document hashes.
  termsOfService: TOS
  contact:
    name: Cochise Ruhulessin
    url: https://www.wizardsofindustry.net
    email: cochise.ruhulessin@wizardsofindustry.net
  license:
    name: MIT
paths:
  /health/:
    summary: Reports the general health of the application.
    x-endpoint:
      classname: HealthEndpoint
      controller:
        qualname: sq.ext.health.HealthCheckCtrl
    parameters:
    - name: timeout
      in: query
      description: Specifies the timeout of the health-check, in milliseconds.
      schema:
        type: integer
    get:
      operationId: get_health
      responses:
        200:
          description: The service is functioning normally.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /version:
    summary: Reports the currently running version of the application.
    x-endpoint:
      classname: VersionEndpoint
      controller:
        qualname: sq.ext.health.VersionCtrl
    get:
      operationId: get_version
      responses:
        200:
          description: Details about the current application deployment.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

  /timestamp:
    summary: >
      Exposes an API to create and verify secure timestamps using an upstream
      Time Stamping Authority (TSA).
    x-endpoint:
      classname: TimestampEndpoint
      controller:
        qualname: hbts.app.ctrl.TimestampCtrl
    post:
      operationId: timestamp
      requestBody:
        description: >
          Contains a SHA-256 hash of the document that must be time stamped.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TimestampingRequest"
      responses:
        201:
          description: >
            The TSA has signed the input data and the result is stored in the
            backend storage system.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecureTimestamp"
        409:
          description: >
            A secure timestamp already exists for the input data.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimestampExists"
        503:
          $ref: "#/components/responses/ServiceNotAvailable"
        default:
          $ref: "#/components/responses/UncaughException"

components:
  responses:
    ServiceNotAvailable:
      description: One or more (upstream) dependencies is not available.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ServiceNotAvailable"

    UncaughException:
      description: An uncaught exception condition interrupted the request-response cycle.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Version:
      type: object
      nullable: false
      example:
        version: "1.0.2"
      required:
      - version
      properties:
        version:
          description: >
            The application version that is currently running.
          type: string

    Health:
      type: object
      nullable: false
      example:
        started: 1528573407847
        uptime: 65293
      required:
      - started
      - uptime
      properties:
        started:
          description: >
            Indicates the date and time at which the application instance was
            started, in milliseconds since the UNIX epoch.
          type: integer
          format: int64
        uptime:
          description: >
            Current application instance lifetime, in milliseconds.
          type: integer
          format: int64

    Error:
      type: object
      nullable: false
      example:
        code: "INTERNAL_SERVER_ERROR"
        detail: "An uncaught exception condition interrupted the request-response cycle."
        hint: "Contact the system administrator if the condition persists."
        id: "67dfd969-98ac-4057-b992-92e19f6ea7ac"
      required:
      - code
      - message
      properties:
        code:
          description: >
            Specifies the exception condition that occurred.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the error
            condition that occurred.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string
        id:
          description: >
            An identifier for this specific exception condition, which may be used
            for debugging purposes.
          type: string
          format: uuid

    SecureTimestamp:
      type: object
      nullable: false
      required:
      - protocol
      - tsa
      properties:
        protocol:
          description: >
            Specifies the protocol that was used to create the secure time stamp.
          type: string
          enum:
          - rfc3161
        tsa:
          description: >
            Specifies the Time Stamping Authority (TSA) that handled the time stamping
            request.
          type: string

    ServiceNotAvailable:
      type: object
      nullable: false
      example:
        code: "SERVICE_NOT_AVAILABLE"
        detail: "The service is currently not available. Try again later."
        hint: "Cease making requests until after the period indicated in the Retry-After header."
      required:
      - code
      - message
      - detail
      - hint
      properties:
        code:
          description: >
            Specifies the cause of service unavailability.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the reasons
            why the service is not available.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string

    TimestampingRequest:
      type: object
      nullable: false
      required:
      - checksum
      properties:
        checksum:
          description: >
            A SHA-256 hash of the document for which a secure time stamp must
            be generated.
          type: string

    TimestampExists:
      type: object
      nullable: false
      example:
        code: "TIMESTAMP_EXISTS"
        detail: "The document (checksum: 2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae
) is already time stamped."
        hint: "Documents that have existing time stamps can not be time stamped again."
      required:
      - code
      - message
      - detail
      - hint
      properties:
        code:
          description: >
            A code identifying the error condition.
          type: string
        message:
          description: >
            Error message targeted at the end-user.
          type: string
        detail:
          description: >
            A message providing a more detailed explanation of the reasons
            why the service is not available.
          type: string
        hint:
          description: >
            A hint indicating on how to resolve the situation.
          type: string
