"""initial

Revision ID: 0d18966e6a17
Revises: 
Create Date: 2018-09-13 00:33:16.441507

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '0d18966e6a17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfc3161',
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tsa', sa.String(), nullable=False),
    sa.Column('crt', sa.String(), nullable=False),
    sa.Column('tsr', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('checksum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfc3161')
    # ### end Alembic commands ###
