"""initial

Revision ID: 7ca213e2522a
Revises: 
Create Date: 2018-09-15 13:53:20.719223

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '7ca213e2522a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfc3161',
    sa.Column('checksum', sa.LargeBinary(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tsa', sa.String(), nullable=False),
    sa.Column('signed', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('document')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfc3161')
    # ### end Alembic commands ###
