"""Contains the base class for :class:`TimestampCtrl`."""
from sq.ctrl import EndpointCtrl

class BaseTimestampCtrl(EndpointCtrl):
    """Generated by SG to serve as an abstract base class for:

        hbts.app.ctrl.TimestampCtrl

    This class encapsulates external dependencies (such as the inversion-of-control
    requirements) and specifies the interface for the concrete implementation.
    """

    async def get(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`TimestampCtrl.get()`
        and should be implemented in the following file:

            ./hbts/ctrl/timestamp/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")

    async def post(self, request, *args, **kwargs):
        """This method specifies the signature for :meth:`TimestampCtrl.post()`
        and should be implemented in the following file:

            ./hbts/ctrl/timestamp/impl.py
        """
        raise NotImplementedError("Subclasses must override this method.")


#pylint: skip-file
# !!! SG MANAGED FILE -- DO NOT EDIT -- VERSION:  !!!
